packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: false
saveExact: true
strictPeerDependencies: true

allowBuilds:
  esbuild: true

overrides:
  "esbuild@>=0.27.3 <0.28.1": 0.28.1
  "vitepress>vite": 6.4.3

catalog:
  "@ascii-reveal/core": workspace:*

minimumReleaseAgeExclude:
  - "@turbo/darwin-64@2.10.8"
  - "@turbo/darwin-arm64@2.10.8"
  - "@turbo/linux-64@2.10.8"
  - "@turbo/linux-arm64@2.10.8"
  - "@turbo/windows-64@2.10.8"
  - "@turbo/windows-arm64@2.10.8"
  - turbo@2.10.8
